version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
      - ASPNETCORE_HTTP_PORTS=5002
    ports:
      - "5001:5001"
      - "5002:5002" 
 
