version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5001:5001"
      - "5002:5002" 

  product.database:
    image: postgres:latest
    container_name: reactivities.db
    environment:
      - POSTGRES_DB=reactivities.db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresql
    volumes:
      - ./.containers/reactivities-db:/var/lib/postgresql/data
    ports:
      - 5432:5432  
 
  pgadmin:
    container_name: pgadmin14_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
